### ISSUE TITLE
Why not flutter_hooks? 

### ISSUE THREAD

**Issue by rrousselGit** [huangbinjie/frhooks#1]
:wave: maintainer of `flutter_hooks` here

Curious: why another package?

**Comment by huangbinjie** [comment]
I have a [state management](https://github.com/huangbinjie/ractor) library depend on react hooks. So when bring my library to flutter,  i implemented `useState` and `useMount` to support my library. But the implementation is too ugly and simple. Then i refactor the hooks part to a individual packages.

**Comment by rrousselGit** [comment]
No problem. But why make another one? 

With this, we have two packages with the same name doing the same thing. Their implementation differ a bit, but the exposed API is strictly the same

So I don't really get it.

**Comment by huangbinjie** [comment]
Yes, agree with you. flutter_hooks2 seems like the second version of flutter_hooks.
Do you think I need to change this package name?

**Comment by rrousselGit** [comment]
Changing the name would be great.

But I'm more concerned about the reasoning for having two.
`flutter_hooks` already have a relatively big user-base and the same features (with `flutter_hooks` having a bit more stuff)

Would that make sense for your library to depend on `flutter_hooks` instead, and contribute to it if there's any missing feature?

**Comment by huangbinjie** [comment]
I want to keep the same api  and usage of react hook.

For example `var [state, setState] = useState(0)`. Instead of `setState`, `flutter_hooks` will rebuild by changing the state...

I think it's hard to change the usage.

flutter_hooks gave me some inspiration for testing. Thank you very much.
If necessary, I will use `flutter_hooks`.

**Comment by rrousselGit** [comment]
`flutter_hooks` allows implementing primitives outside of the library itself (by subclassing `Hook`). 

This is done on purpose in case peoples don't like existing hooks or wants to make their own primitives.

Of course, you're free to do however you want to. But I'd personally prefer if we could merge the efforts. That is because hooks allow content-creators to make their own open source hooks. 

So if half of them use one hook implementation, and the other half use another one, then things could get really messy.

**Comment by huangbinjie** [comment]
I'm not that ambitious. My goal now is just to support my library。And the whole Internal implementation between `frhooks` and `flutter_hooks` is very different. 

Have a nice weekend.
